### PR TITLE
Fixed Manager memory leak while reconnecting in .NET 4.5

### PR DESCRIPTION
**Pull request by blurt**

### CODE REVIEW

**Comment by blurt** [comment]
@mattqs would you be able to publish a new NuGet package to include the last few fixes?

**Comment by mattqs** [comment]
@blurt yes, this will be published be the end of this week

**Comment by blurt** [comment]
@mattqs Will this be a release or pre-release version? Given the fixes included, perhaps a full release?

**Comment by mattqs** [comment]
Nuget does not allow making a full release if one of the dependencies is a pre-release. https://www.nuget.org/packages/WebSocket4Net/ is still a pre-release it is going to be a pre-release until WebSocket4Net is full release.

**Comment by mattqs** [comment]
Published now: 1.0.0.1-beta1

**Comment by blurt** [comment]
Thanks Matthias! I appreciate the quick turn-around.

**Pull request merged**
